higher-ranked-exception-types.pdf: *.lhs2tex *.tex
	lhs2tex -o higher-ranked-exception-types.tex higher-ranked-exception-types.lhs2tex
	latexmk -pdf higher-ranked-exception-types.tex
	evince higher-ranked-exception-types.pdf

*.lhs2tex:
*.tex:
